### ISSUE TITLE
While running any command of pftool getting segmentation fault

### ISSUE THREAD

**Issue by swapng** [pftool/pftool#95]
**I ran below commands,**
1. pfls -R /home/linux-5.11 
2. mpirun -np 4 /usr/local/bin/pftool -w 1 -l -r -p /home/linux-5.11
Checked with other commands as well but getting the same issue.

**Below is the message from stdout,** 

```
INFO  HEADER   ========================  TestJob  ============================
INFO  HEADER   Starting Path: /home/linux-5.11
INFO  HEADER   Source-type: POSIX_Path
 *** Process received signal ***
Signal: Segmentation fault (11)
Signal code: Invalid permissions (2)
Failing at address: 0x55769efe7770
[ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f1ac3f5f3c0]
[ 1] [0x55769efe7770]
*** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node Lenovo-V1 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

```
**Stack Trace**

```
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pftool...
[New LWP 22907]
[New LWP 22911]
[New LWP 22915]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/pftool -w 1 -l -r -p /home/linux-5.11'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055769efe7770 in ?? ()
[Current thread is 1 (Thread 0x7f1ac3b59740 (LWP 22907))]
(gdb) bt
#0  0x000055769efe7770 in ?? ()
#1  0x00007f1ac3f7fd19 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007f1ac3f80605 in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#3  0x000055769deea051 in std::tr1::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/9/tr1/shared_ptr.h:983
#4  std::tr1::__shared_ptr<Path, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/9/tr1/shared_ptr.h:539
#5  std::tr1::shared_ptr<Path>::~shared_ptr (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/9/tr1/shared_ptr.h:983
#6  get_base_path (base_path=0x7f1ac3f5bbb0 <__GI___pthread_key_create> "\363\017\036\372L\215\005\205", <incomplete sequence \307>, item=0xffffff4b, wildcard=<optimized out>) at pfutils.cpp:269
#7  0x0000000000000000 in ?? ()
```

**Note:** Running pftool on Linux mint-20

**Comment by gransom** [comment]
This is very likely the result of pftool bumping up against stack size limits.  Pftool allocates a large amount of stack space and very frequently overwhelms the default stack size ulimit values.
I recommend setting the stack size ulimit to 'unlimited' and retrying.

**Comment by swapng** [comment]
@gransom Thank you for your suggestion, I set stack size ulimit to unlimited and retry the same command but still getting segfault.

FYI, I'm using **Open MPI 4.1.1** and **OpenSSL 1.1.1f**

**My current limits configuration is,**

```
- core file size          (blocks, -c) unlimited

- data seg size           (kbytes, -d) unlimited

- scheduling priority             (-e) 0

- file size               (blocks, -f) unlimited

- pending signals                 (-i) 46747

- max locked memory       (kbytes, -l) unlimited

- max memory size         (kbytes, -m) unlimited

- open files                      (-n) 1024

- pipe size            (512 bytes, -p) 8

- POSIX message queues     (bytes, -q) 819200

- real-time priority              (-r) 0

- stack size              (kbytes, -s) unlimited

- cpu time               (seconds, -t) unlimited

- max user processes              (-u) 46747

- virtual memory          (kbytes, -v) unlimited

- file locks                      (-x) unlimited

```

**Comment by gransom** [comment]
Thank you for including the openssl version.  I expect you've noticed the similarities between this issue and #94.
Just to give an update ( same as attached to that issue ), we believe that this segfault is linked to the use of a deprecated libcrytpo interface by pftool.  We're currently working on a fix to allow for compatibility with modern openssl versions, while not breaking some of our older systems.
That fix will likely be pushed to a new branch, and we'll update here when that occurs.  At that time, we're hopping you can confirm that the segfault issue has indeed been corrected.

**Comment by swapng** [comment]
Sure I'll confirm once this segfault issue gets resolved. 
**Update**:- I configured pftool with debug level zero and with c++11 or c++15 or c++17 versions by using CXXFLAGS. 
After compilation with this configuration, **pfls** command is working **(only with a single node)**.  Also, I tried **pfcp** and **pfcm** but the commands are not working. Getting the same segfault.

**Comment by gransom** [comment]
We've tested on centos8 with matching openssl and openmpi versions and haven't been able to reproduce thus far.
Just in case, I wanted to confirm you've done a completely clean build ( 'make distclean', 'autoreconf', 'configure', 'make' or 'make install' ).  If the problem is still persisting, can you confirm this segfault is consistently reproducible simply via that original 'pfls -R <tgt-fs-tree>'?

**Comment by dmp265** [comment]
You may also want to double check your ulimit values, since calling 'ulimit -s unlimited' does not cause a persistent change across sessions.
